services:
  name-client:
    image: ap-nimbus-client-direct
    depends_on:
      name-postgres:
        condition: service_healthy
      name-app-manager:
        condition: service_started
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "4240:80"
    restart: unless-stopped
    volumes:
      - volume-ap-nimbus-client:/opt/django/media
    env_file:
      - ./env
    networks:
      - ap-nimbus-network

  name-app-manager:
    image: cardiacmodelling/ap-nimbus-app-manager:2.0.0
    restart: unless-stopped
    volumes:
      - volume-ap-nimbus-app-manager:/home/appredict/apps/app-manager
    networks:
      - ap-nimbus-network

  name-postgres:
    image: postgres:17.10-trixie
    restart: unless-stopped
    volumes:
      - volume-ap-nimbus-postgres:/var/lib/postgresql/data
    env_file:
      - ./env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ap-nimbus-network

volumes:
  volume-ap-nimbus-client:
  volume-ap-nimbus-postgres:
  volume-ap-nimbus-app-manager:

networks:
  ap-nimbus-network:
