# Generated by Django 3.2.10 on 2022-01-06 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_auto_20220105_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, help_text="A short title to identify this simulation.")),
                ('notes', models.TextField(blank=True, default='', help_text="Any notes related to this simulation. Please note: These will also be visible to admin users.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pacing_frequency', models.FloatField(default=0.05, help_text='(in Hz) Frequency of pacing (between 0.05 and 5).')),
                ('maximum_pacing_time', models.FloatField(default=5, help_text='(in mins) Maximum pacing time (between 0 and 120).')),
                ('ion_current_type', models.CharField(choices=[('pIC50', 'pIC50'), ('IC50', 'IC50')], max_length=255, help_text="Ion current type.")),
                ('ion_units', models.CharField(choices=[('-log(M)', '-log(M)'), ('M', 'M'), ('µM', 'µM'), ('nM', 'nM')], max_length=255, help_text="Ion current units.")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.cellmlmodel')),
            ],
            options={
                'unique_together': {('title', 'author')},
            },
        ),
        migrations.CreateModel(
            name='SimulationIonCurrentParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.FloatField(blank=True, null=True, help_text="> 0 for IC50.")),
                ('hill_coefficient', models.FloatField(default=1, help_text="Between 0.1 and 5.")),
                ('saturation_level', models.FloatField(default=0, help_text="Level of peak current relative to control at a very large compound concentration (between 0 and 1).\n- For an inhibitor this is in the range 0% (default) to <100% (compound has no effect).\n- For an activator Minimum > 100% (no effect) to Maximum 500% (as a guideline).")),
                ('spread_of_uncertainty', models.FloatField(blank=True, null=True, default=1, help_text="Spread of uncertainty (between 0 and 2).\nDefaults are estimates based on a study by Elkins et all.\nIdeally all these numbers would be replaced based on the spread you observe in fitted pIC50s.")),
                ('ion_current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.ioncurrent')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulations.simulation')),
            ],
        ),
    ]
