# Generated by Django 4.0.2 on 2022-02-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='ap_predict_messages',
            new_name='api_errors',
        ),
        migrations.AddField(
            model_name='simulation',
            name='messages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
