# Generated by Django 4.0.2 on 2022-02-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='progress',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
    ]
