# Generated by Django 3.2.11 on 2022-02-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='ap_predict_last_called',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
