# Generated by Django 4.0.2 on 2022-03-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_simulation_pkpd_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='intermediate_point_count',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='4', help_text='Count of plasma concentrations between the minimum and maximum (between 0 and 10).', max_length=255),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='intermediate_point_log_scale',
            field=models.BooleanField(blank=True, default=True, help_text='Use log scale for intermediate points.'),
        ),
    ]
