# Generated by Django 4.0.7 on 2022-11-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0004_alter_simulation_intermediate_point_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='stdout',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
