# Generated by Django 4.0.7 on 2022-11-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0005_simulation_stdout'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='version_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
