# Generated by Django 4.0.7 on 2022-11-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0006_simulation_version_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='stdout',
            new_name='STDOUT',
        ),
    ]
