# Generated by Django 3.2.10 on 2022-01-06 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IonCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A (unique) short name for the kurrent e.g. <em>IKr</em>.', max_length=255, unique=True)),
                ('alternative_name', models.CharField(blank=True, help_text='Alternative name to display alongside the name, e.g. <em>herg</em> for the name <em>IKr</em> which would be displayed as <em>IKr (herg)</em>.', max_length=255)),
                ('metadata_tags', models.CharField(help_text='A set of metadata tags (comma seperated) in the cellml that confirms the presence of the current e.g. <em>membrane_fast_sodium_current_conductance, membane_fast_sodium_current_conductance_scaling_factor</em>.', max_length=255)),
                ('channel_protein', models.CharField(max_length=255, blank=True)),
                ('gene', models.CharField(max_length=255, blank=True)),
                ('description', models.CharField(max_length=255, blank=True)),
                ('default_hill_coefficient', models.FloatField(default=1, help_text='Default hill coefficient (between 0.1 and 5).')),
                ('default_saturation_level', models.FloatField(default=0, help_text='The (default) level of peak current relative to control at a very large compound concentration. For an inhibitor this is in the range 0% (default) to <100% (compound has no effect).<br /> For an activator Minimum > 100% (no effect) to Maximum 500% (as a guideline).')),
                ('default_spread_of_uncertainty', models.FloatField(default=1, help_text='Default guiding value for the ion current (between 0 and 2).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CellmlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predefined', models.BooleanField(default=False, help_text='Show this model as a predefined model to all users. (This option is only available to admins).')),
                ('name', models.CharField(help_text="The name of the model, e.g. <em>O'Hara-Rudy</em>.", max_length=255)),
                ('description', models.CharField(default='', help_text='A short description e.g. <em>human ventricular cell model (endocardial)</em>.', max_length=255)),
                ('version', models.CharField(blank=True, default='', help_text='An (optional) version, e.g. <em>CiPA-v1.0</em>.', max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, help_text='The year this specific model (version) was published e.g. <em>2017</em>.')),
                ('cellml_link', models.URLField(blank=True, help_text='An (optional) link to a description of the cellml. e.g. on <em>www.cellml.org</em>.', max_length=255, null=True)),
                ('paper_link', models.URLField(blank=True, help_text='An (optional) link to a paper related to the model.', max_length=255, null=True)),
                ('ap_predict_model_call', models.CharField(blank=True, help_text='call to pass to Ap Predict with --model parameter e.g. <em> 1</em> or <em> shannon_wang_puglisi_weber_bers_2004</em>. This option is only available to admins and cannot be combianed with uploading a cellml file.', max_length=255, null=True)),
                ('cellml_file', models.FileField(blank=True, help_text='Please upload the cellml file here.', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ion_currents', models.ManyToManyField(blank=True, help_text='Ion currents used. This selection is ignored when a cellml file is uploaded. To edit the selection for modules using a cellml file, see the admin interface.', to='files.IonCurrent')),
            ],
            options={
                'unique_together': {('name', 'author')},
            },
        ),
    ]
