# Generated by Django 3.2.9 on 2022-01-04 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CellmlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predefined', models.BooleanField(default=False, help_text='Show this model as a predefined model to all users. (This option is only available to admins).')),
                ('name', models.CharField(help_text="The name of the model, e.g. <em>O'Hara-Rudy</em>.", max_length=255, unique=True)),
                ('description', models.CharField(default='', help_text='A short description e.g. <em>human ventricular cell model (endocardial)</em>.', max_length=255)),
                ('version', models.CharField(blank=True, default='', help_text='An (optional) version, e.g. <em>CiPA-v1.0</em>.', max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, help_text='The year this specific model (version) was published e.g. <em>2017</em>.')),
                ('cellml_link', models.URLField(blank=True, help_text='An (optional) link to a description of the cellml. e.g. on <em>www.cellml.org</em>.', max_length=255, null=True)),
                ('paper_link', models.URLField(blank=True, help_text='An (optional) link to a paper related to the model.', max_length=255, null=True)),
                ('ap_predict_model_call', models.CharField(blank=True, help_text='call to pass to Ap Predict with --model parameter e.g. <em> 1</em> or <em> shannon_wang_puglisi_weber_bers_2004</em>. This option is only available to admins and cannot be combianed with uploading a cellml file.', max_length=255, null=True)),
                ('cellml_file', models.FileField(blank=True, help_text='Please upload the cellml file here.', upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
