# Generated by Django 3.2.9 on 2021-12-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellmlmodel',
            name='cellml_file',
            field=models.FileField(blank=True, help_text='Please upload the cellml file here.', upload_to=''),
        ),
    ]
