# Generated by Django 3.2.9 on 2021-12-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellmlmodel',
            name='version',
            field=models.CharField(blank=True, default='', help_text='An (optional) version, e.g. <em>CiPA-v1.0</em>.', max_length=255),
        ),
    ]
