# Generated by Django 4.0.7 on 2022-11-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20220105_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellmlmodel',
            name='ap_predict_model_call',
            field=models.CharField(blank=True, help_text='call to pass to Ap Predict with --model parameter e.g. <em>1</em> or <em> shannon_wang_puglisi_weber_bers_2004</em>. \nThis option is only available to admins and cannot be combianed with uploading a cellml file.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cellmlmodel',
            name='version',
            field=models.CharField(blank=True, default='', help_text='An (optional) version, e.g. <em>(endo)</em>.', max_length=255),
        ),
    ]
