# Generated by Django 3.2.9 on 2021-12-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_cellmlmodel_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellmlmodel',
            name='cellml_file',
            field=models.FileField(help_text='Please upload the cellml file here.', unique=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='cellmlmodel',
            name='name',
            field=models.CharField(help_text="The name of the model, e.g. <em>O'Hara-Rudy</em>.", max_length=255, unique=True),
        ),
    ]
