# Generated by Django 3.2.9 on 2021-12-13 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0003_auto_20211210_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellmlmodel',
            name='predefined',
        ),
        migrations.AddField(
            model_name='cellmlmodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cellmlmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cellmlmodel',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('moderated', 'Moderated')], default='public', help_text='Moderated = public and checked by a moderator<br/>Public = anyone can view<b/>Private = only you can view', max_length=16),
            preserve_default=False,
        ),
    ]
