# Generated by Django 4.0.8 on 2022-11-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20221102_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppredictLookupTableManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest', models.TextField(default='')),
                ('response_text', models.TextField(default='')),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
