# Generated by Django 3.2.9 on 2021-12-13 16:46

import django.core.validators
from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_cellmlmodel_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellmlmodel',
            name='cellml_file',
            field=models.FileField(help_text='Please upload the cellml file here.', unique=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cellml']), files.models.validate_is_xml]),
        ),
    ]
