# Generated by Django 4.0.8 on 2022-11-02 18:10

import os
import re

from django.conf import settings
from django.db import migrations


def create_manifest(apps, schema_editor):
    AppredictLookupTableManifest = apps.get_model('files', 'AppredictLookupTableManifest')
    manifest_file = os.path.join(settings.BASE_DIR, 'files', 'migrations', 'appredict_lookup_table_manifest.txt')
    with open(manifest_file) as f:
        response_text = f.read().strip()

    matches = set(re.findall(r'(.*)_\dd_.*\n', response_text))
    manifest = '\n'.join(matches)
    AppredictLookupTableManifest.objects.create(manifest=manifest, response_text=response_text)



class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_appredictlookuptablemanifest'),
    ]

    operations = [
        migrations.RunPython(create_manifest),
    ]
