name: docker-build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      context: ./docker/
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      distribute: true
      sign: auto
      meta-images: cardiacmodelling/ap-nimbus-client-direct
      meta-tags: |
        type=semver,pattern={{version}},value=2.0.0
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
