name: build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Start PostgreSQL on Ubuntu
      run: |
        sudo systemctl start postgresql.service
        pg_isready
    - name: Create client user
      run: |
        sudo -u postgres psql --command="CREATE USER client PASSWORD 'not-so-secret django db password'" --command="\du"
        sudo -u postgres psql --command="ALTER USER client CREATEDB;" --command="\du"
    - name: Edit git settings
      run: |
        git config --global user.email "github.actions@CI.com"  
        git config --global user.name "Github Actions"
    - name: Checkout repository and submodules
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install flake8 pytest pytest-django
        pip install -r requirements/test.txt
    - name: Lint with flake8
      run: |
        python -m flake8 client
    - name: Test sorting with isort
      run: |
        python -m isort --verbose --check-only --diff recursive client
    - name: Setup secrets
      run: |
        tar -xvf .actions.tar
    - name: Test with pytest
      run: |
        python -m pytest --cov=client --cov-config=client/.coveragerc client
      env:
        DATABASE_URL: postgres://client:not-so-secret django db password@localhost:5432/client
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
